apiVersion: v1
kind: Service
metadata:
  labels:
    application: "{{{APPLICATION_ID}}}"
    environment: "{{{ENVIRONMENT}}}"
    component: "{{{COMPONENT}}}"
  name: "{{{APPLICATION}}}"
  namespace: "{{{NAMESPACE}}}"
  annotations:
    janitor/ttl: "{{{RESOURCE_TTL}}}"
spec:
  selector:
    application: "{{{APPLICATION_ID}}}"
    environment: "{{{ENVIRONMENT}}}"
    component: "{{{COMPONENT}}}"
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
